### ISSUE TITLE
minus sign removed from negative rem values

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/sass-compiler#100]
**Originally by @marlonrichert**

___
Given the following SCSS:
```
* {
	    position: absolute;
	    top: -.0625rem;
	    bottom: -.0625rem;
	    left: -2.8125rem;
	    margin: -0.0625rem;
	    margin-top: -1px;
}
```
This compiles to the following CSS:
```
* {
	    position: absolute;
	    top: .0625rem;
	    bottom: .0625rem;
	    left: 2.8125rem;
	    margin: 0.0625rem;
	    margin-top: -1px;
}
```

Notice how the negative rem values have become positive!

**Comment by ctoddy** [comment]
@marlonrichert how was this resolved? Currently running into the same issue and can't find any research on it. Thanks :)

**Comment by marlonrichert** [comment]
@ctoddy Looks like it was never resolved. If it was, there would be a commit listed here. You’re probably better off using [the official Sass compiler](https://sass-lang.com/). It looks like the Vaadin fork [has not been updated since 2015](https://github.com/vaadin/sass-compiler/commits/master). 🙂

**Comment by ctoddy** [comment]
Thank you!
