### ISSUE TITLE
Next release with minimized output feature

### ISSUE THREAD

**Issue by danjee** [vaadin/sass-compiler#8]
When are you planning the release for compressed output? I use 0.9.12 from maven public repository and this feature is not included. Do you have a roadmap for releases?
Thank you

**Comment by samie** [comment]
We have no roadmap for the Sass compiler currently and it is very unlikely that we add this for it. However, it should be possible to have a separate gzip step using Maven/Ant.

**Comment by danjee** [comment]
I see, I saw that the github version is not the same as the one from central maven repository and I assumed that this github code will be he 0.9.13 version. I was thinking of compressed like a minimized version of the output string.

**Comment by hesara** [comment]
Actually, this should be quite easy to add in our sass compiler, and could be added if we make a maintenance version of the sass compiler sometime soon. However, I'd rename the currently unreleased minify option first because it conflicts with the most logical name for this option.

**Comment by danjee** [comment]
That will be great! Thanx you

**Comment by danjee** [comment]
Any news on this? Thank you

**Comment by danjee** [comment]
Thank you
